import ExportView from "./_ExportView";
import type { FullExportData } from "@/components/pdfx/FullExportDocument";

const DUMMY: FullExportData = {
  generatedAt: "2026-05-22",
  dateRange: { start: "2026-04-22", end: "2026-05-22" },
  profile: {
    full_name: "Amara Johnson",
    nickname: "Amara",
    dob: "1995-08-14",
    scd_type: "HbSS",
    height: 165,
    weight: 62,
    preferred_hospital: "King's College Hospital",
    blood_type: "O+",
    allergies: ["Penicillin"],
  },
  streak: {
    current: 7,
    longest: 23,
    lastLogDate: "2026-05-22",
    badgesEarned: 5,
  },
  stats: {
    totalDaysLogged: 24,
    avgPain: 3.4,
    avgHydration: 1550,
    avgMood: 3.1,
    avgSleep: 7.2,
    avgSteps: 4800,
    avgHeartRate: 78,
  },
  topSymptoms: [
    { name: "Fatigue", count: 14 },
    { name: "Joint pain", count: 11 },
    { name: "Headache", count: 7 },
    { name: "Shortness of breath", count: 4 },
    { name: "Swollen hands", count: 3 },
  ],
  topTriggers: [
    { name: "Cold weather", count: 9 },
    { name: "Dehydration", count: 8 },
    { name: "Stress", count: 6 },
    { name: "Overexertion", count: 4 },
  ],
  medications: [
    {
      id: "1",
      name: "Hydroxyurea",
      dosage: "500mg",
      frequency: "Every Day",
      type: "tablet",
      category: "Disease-modifying",
      prescribed_by: "Dr. Osei-Mensah",
      is_active: true,
      adherence: { taken: 22, scheduled: 30 },
    },
    {
      id: "2",
      name: "Folic Acid",
      dosage: "5mg",
      frequency: "Every Day",
      type: "tablet",
      category: "Supportive",
      prescribed_by: "Dr. Osei-Mensah",
      is_active: true,
      adherence: { taken: 28, scheduled: 30 },
    },
    {
      id: "3",
      name: "Ibuprofen",
      dosage: "400mg",
      frequency: "As Needed",
      type: "tablet",
      category: "Pain management",
      prescribed_by: null,
      is_active: true,
      adherence: { taken: 6, scheduled: 6 },
    },
    {
      id: "4",
      name: "Penicillin V",
      dosage: "250mg",
      frequency: "Twice daily",
      type: "tablet",
      category: "Supportive",
      prescribed_by: "Dr. Osei-Mensah",
      is_active: false,
      adherence: null,
    },
  ],
  healthLogs: [
    {
      date: "2026-04-22",
      pain_level: 2,
      mood: 4,
      hydration: 1750,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: "Good day overall",
      is_repaired: false,
    },
    {
      date: "2026-04-23",
      pain_level: 4,
      mood: 3,
      hydration: 1250,
      symptoms: ["Joint pain", "Fatigue"],
      triggers: ["Cold weather"],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-04-24",
      pain_level: 6,
      mood: 2,
      hydration: 1000,
      symptoms: ["Joint pain", "Headache"],
      triggers: ["Cold weather", "Stress"],
      notes: "Rough night",
      is_repaired: false,
    },
    {
      date: "2026-04-25",
      pain_level: 5,
      mood: 2,
      hydration: 1250,
      symptoms: ["Joint pain", "Fatigue"],
      triggers: ["Dehydration"],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-04-26",
      pain_level: 3,
      mood: 3,
      hydration: 1500,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-04-27",
      pain_level: 2,
      mood: 4,
      hydration: 2000,
      symptoms: [],
      triggers: [],
      notes: "Felt much better",
      is_repaired: false,
    },
    {
      date: "2026-04-28",
      pain_level: 1,
      mood: 4,
      hydration: 2250,
      symptoms: [],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-04-29",
      pain_level: 0,
      mood: 5,
      hydration: 2000,
      symptoms: [],
      triggers: [],
      notes: "Best day in weeks",
      is_repaired: false,
    },
    {
      date: "2026-04-30",
      pain_level: 2,
      mood: 4,
      hydration: 1750,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-01",
      pain_level: 3,
      mood: 3,
      hydration: 1500,
      symptoms: ["Fatigue", "Headache"],
      triggers: ["Stress"],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-02",
      pain_level: 2,
      mood: 4,
      hydration: 1750,
      symptoms: [],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-03",
      pain_level: 4,
      mood: 3,
      hydration: 1250,
      symptoms: ["Swollen hands", "Joint pain"],
      triggers: ["Cold weather", "Overexertion"],
      notes: "Overdid it at work",
      is_repaired: false,
    },
    {
      date: "2026-05-05",
      pain_level: 5,
      mood: 2,
      hydration: 1000,
      symptoms: ["Joint pain", "Shortness of breath"],
      triggers: ["Dehydration"],
      notes: null,
      is_repaired: true,
    },
    {
      date: "2026-05-06",
      pain_level: 4,
      mood: 3,
      hydration: 1500,
      symptoms: ["Fatigue", "Joint pain"],
      triggers: ["Stress"],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-07",
      pain_level: 3,
      mood: 3,
      hydration: 1750,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-08",
      pain_level: 2,
      mood: 4,
      hydration: 2000,
      symptoms: [],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-09",
      pain_level: 1,
      mood: 5,
      hydration: 2250,
      symptoms: [],
      triggers: [],
      notes: "Great energy today",
      is_repaired: false,
    },
    {
      date: "2026-05-10",
      pain_level: 2,
      mood: 4,
      hydration: 1750,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-13",
      pain_level: 7,
      mood: 1,
      hydration: 750,
      symptoms: ["Joint pain", "Shortness of breath", "Headache"],
      triggers: ["Cold weather", "Dehydration", "Stress"],
      notes: "Crisis warning signs",
      is_repaired: false,
    },
    {
      date: "2026-05-14",
      pain_level: 6,
      mood: 2,
      hydration: 1000,
      symptoms: ["Joint pain", "Fatigue"],
      triggers: ["Dehydration"],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-15",
      pain_level: 5,
      mood: 2,
      hydration: 1250,
      symptoms: ["Joint pain", "Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-16",
      pain_level: 4,
      mood: 3,
      hydration: 1500,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-19",
      pain_level: 3,
      mood: 3,
      hydration: 1750,
      symptoms: ["Fatigue"],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
    {
      date: "2026-05-22",
      pain_level: 2,
      mood: 4,
      hydration: 1750,
      symptoms: [],
      triggers: [],
      notes: null,
      is_repaired: false,
    },
  ],
  dailySummaries: [],
};

export default function ExportTestPage() {
  return <ExportView data={DUMMY} testMode />;
}
