import React, { useState } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Alert,
  Share,
} from "react-native";
import { StatusBar } from "expo-status-bar";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  User,
  Settings,
  FileText,
  Download,
  Share as ShareIcon,
  ChevronDown,
  ChevronRight,
  Calendar,
  Activity,
  Heart,
  Award,
  LogOut,
  Edit,
  Phone,
  Shield,
} from "lucide-react-native";
import { LinearGradient } from "expo-linear-gradient";
import { useAppStore } from "../../store/appStore";
import { mockBadges } from "../../types";
import { fonts } from "@/utils/fonts";

const HEMO_GRADIENT = ["#D09F9A", "#A9334D", "#781D11"];

export default function ProfileScreen() {
  const insets = useSafeAreaInsets();
  const [expandedSection, setExpandedSection] = useState(null);

  const { currentUser, healthStreak, healthData, emergencyContacts, onboardingData } = useAppStore();

  const displayAge = onboardingData?.dob
    ? Math.floor((Date.now() - new Date(onboardingData.dob).getTime()) / (365.25 * 24 * 60 * 60 * 1000))
    : currentUser?.age;
  const displayScdType = onboardingData?.scdType || currentUser?.scdType;
  const totalLogs = healthData?.length || 0;
  const unlockedBadges = mockBadges.filter((b) => b.unlockedAt).length;
  const daysActive = currentUser?.joinedDays || 0;

  const toggleSection = (section) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  const handleShareHealthSummary = async () => {
    try {
      const summary = `
Hemo - Health Summary
Patient: ${currentUser?.name}
Age: ${displayAge}
SCD Type: ${displayScdType}
Health Streak: ${healthStreak} days
Date: ${new Date().toLocaleDateString()}

This summary was generated by Hemo mobile app.
      `.trim();

      await Share.share({
        message: summary,
        title: "Health Summary",
      });
    } catch (error) {
      Alert.alert("Error", "Unable to share health summary");
    }
  };

  const handleExportData = () => {
    Alert.alert(
      "Export Health Data",
      "Your health data will be prepared for download. You will receive a comprehensive PDF report.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Export",
          onPress: () =>
            Alert.alert("Success", "Health data export initiated!"),
        },
      ],
    );
  };

  const healthRecordSections = [
    {
      id: "diagnosis",
      title: "Diagnosis Information",
      icon: FileText,
      color: "#DC2626",
      items: [
        { label: "Primary Diagnosis", value: displayScdType ? `Sickle Cell Disease (${displayScdType})` : "Not specified" },
        { label: "Date of Diagnosis", value: "March 15, 2010" },
        { label: "Diagnosing Physician", value: "Dr. Sarah Johnson" },
        { label: "Current Status", value: "Stable, Managing Well" },
      ],
    },
    {
      id: "medications",
      title: "Current Medications",
      icon: Heart,
      color: "#059669",
      items: onboardingData?.medications?.length > 0
        ? onboardingData.medications.map((med) => ({
            label: med.name,
            value: `${med.dosage} ${med.frequency}`.trim(),
          }))
        : [{ label: "Medications", value: "No medications added yet" }],
    },
    {
      id: "allergies",
      title: "Allergies & Reactions",
      icon: Shield,
      color: "#EF4444",
      items: [
        { label: "Drug Allergies", value: "Codeine (severe reaction)" },
        { label: "Environmental", value: "None known" },
        { label: "Food Allergies", value: "None known" },
        { label: "Last Updated", value: "August 20, 2024" },
      ],
    },
    {
      id: "vaccinations",
      title: "Vaccination History",
      icon: Activity,
      color: "#A9334D",
      items: [
        { label: "Pneumococcal", value: "Up to date (2024)" },
        { label: "Meningococcal", value: "Due for booster" },
        { label: "Influenza", value: "Annual - Current" },
        { label: "COVID-19", value: "Boosted (Sept 2024)" },
      ],
    },
  ];

  const ProfileHeader = () => (
    <LinearGradient
      colors={HEMO_GRADIENT}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 1 }}
      style={{
        paddingTop: insets.top + 20,
        paddingHorizontal: 20,
        paddingBottom: 30,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        overflow: "hidden",
      }}
    >
      {/* Decorative shapes */}
      <View style={{ position: "absolute", width: 200, height: 200, borderRadius: 999, backgroundColor: "#D09F9A", opacity: 0.15, top: -60, right: -40 }} />
      <View style={{ position: "absolute", width: 140, height: 140, borderRadius: 999, backgroundColor: "#781D11", opacity: 0.15, bottom: -20, left: -40 }} />
      <View
        style={{
          flexDirection: "row",
          alignItems: "center",
          marginBottom: 20,
        }}
      >
        <View
          style={{
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 40,
            padding: 20,
            marginRight: 16,
          }}
        >
          <User size={32} color="#ffffff" />
        </View>

        <View style={{ flex: 1 }}>
          <Text
            style={{
              fontFamily: fonts.bold,
              fontSize: 24,
              color: "#ffffff",
              marginBottom: 4,
            }}
          >
            {currentUser?.name}
          </Text>

          <Text
            style={{
              fontFamily: fonts.medium,
              fontSize: 16,
              color: "rgba(248,233,231,0.8)",
              marginBottom: 2,
            }}
          >
            Age {displayAge} • {displayScdType}
          </Text>

          <Text
            style={{
              fontFamily: fonts.regular,
              fontSize: 14,
              color: "rgba(248,233,231,0.8)",
            }}
          >
            Member since {currentUser?.createdAt?.toLocaleDateString()}
          </Text>
        </View>

        <TouchableOpacity
          style={{
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 10,
            padding: 10,
          }}
        >
          <Edit size={20} color="#ffffff" />
        </TouchableOpacity>
      </View>

      {/* Stats Row */}
      <View
        style={{
          flexDirection: "row",
          justifyContent: "space-around",
          backgroundColor: "rgba(255,255,255,0.1)",
          borderRadius: 16,
          paddingVertical: 16,
        }}
      >
        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontFamily: fonts.bold,
              fontSize: 24,
              color: "#ffffff",
            }}
          >
            {healthStreak}
          </Text>
          <Text
            style={{
              fontFamily: fonts.regular,
              fontSize: 12,
              color: "rgba(248,233,231,0.8)",
            }}
          >
            Day Streak
          </Text>
        </View>

        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontFamily: fonts.bold,
              fontSize: 24,
              color: "#ffffff",
            }}
          >
            {totalLogs}
          </Text>
          <Text
            style={{
              fontFamily: fonts.regular,
              fontSize: 12,
              color: "rgba(248,233,231,0.8)",
            }}
          >
            Total Logs
          </Text>
        </View>

        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontFamily: fonts.bold,
              fontSize: 24,
              color: "#ffffff",
            }}
          >
            {unlockedBadges}
          </Text>
          <Text
            style={{
              fontFamily: fonts.regular,
              fontSize: 12,
              color: "rgba(248,233,231,0.8)",
            }}
          >
            Badges
          </Text>
        </View>

        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontFamily: fonts.bold,
              fontSize: 24,
              color: "#ffffff",
            }}
          >
            {daysActive}
          </Text>
          <Text
            style={{
              fontFamily: fonts.regular,
              fontSize: 12,
              color: "rgba(248,233,231,0.8)",
            }}
          >
            Days Active
          </Text>
        </View>
      </View>
    </LinearGradient>
  );

  const QuickAction = ({ title, subtitle, icon: Icon, color, onPress }) => (
    <TouchableOpacity
      onPress={onPress}
      style={{
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#F8E9E7",
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#781D11",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 3,
        elevation: 2,
      }}
    >
      <View
        style={{
          backgroundColor: `${color}15`,
          borderRadius: 10,
          padding: 12,
          marginRight: 16,
        }}
      >
        <Icon size={22} color={color} />
      </View>

      <View style={{ flex: 1 }}>
        <Text
          style={{
            fontFamily: fonts.semibold,
            fontSize: 16,
            color: "#09332C",
            marginBottom: 2,
          }}
        >
          {title}
        </Text>
        <Text
          style={{
            fontFamily: fonts.regular,
            fontSize: 13,
            color: "#9CA3AF",
          }}
        >
          {subtitle}
        </Text>
      </View>

      <ChevronRight size={20} color="#C4A8A4" />
    </TouchableOpacity>
  );

  const HealthRecordSection = ({ section }) => {
    const isExpanded = expandedSection === section.id;

    return (
      <View
        style={{
          backgroundColor: "#ffffff",
          borderRadius: 12,
          marginBottom: 12,
          borderWidth: 1,
          borderColor: "#F8E9E7",
          overflow: "hidden",
          shadowColor: "#781D11",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 3,
          elevation: 2,
        }}
      >
        <TouchableOpacity
          onPress={() => toggleSection(section.id)}
          style={{
            padding: 16,
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: isExpanded ? `${section.color}05` : "#ffffff",
          }}
        >
          <View
            style={{
              backgroundColor: `${section.color}15`,
              borderRadius: 8,
              padding: 8,
              marginRight: 12,
            }}
          >
            <section.icon size={20} color={section.color} />
          </View>

          <Text
            style={{
              fontFamily: fonts.semibold,
              fontSize: 16,
              color: "#09332C",
              flex: 1,
            }}
          >
            {section.title}
          </Text>

          {isExpanded ? (
            <ChevronDown size={20} color="#C4A8A4" />
          ) : (
            <ChevronRight size={20} color="#C4A8A4" />
          )}
        </TouchableOpacity>

        {isExpanded && (
          <View
            style={{
              paddingHorizontal: 16,
              paddingBottom: 16,
              borderTopWidth: 1,
              borderTopColor: "#F8E9E7",
            }}
          >
            {section.items.map((item, index) => (
              <View
                key={index}
                style={{
                  flexDirection: "row",
                  justifyContent: "space-between",
                  paddingVertical: 8,
                  borderBottomWidth: index < section.items.length - 1 ? 1 : 0,
                  borderBottomColor: "#F8E9E7",
                }}
              >
                <Text
                  style={{
                    fontFamily: fonts.regular,
                    fontSize: 14,
                    color: "#9CA3AF",
                    flex: 1,
                  }}
                >
                  {item.label}:
                </Text>
                <Text
                  style={{
                    fontFamily: fonts.medium,
                    fontSize: 14,
                    color: "#09332C",
                    flex: 2,
                    textAlign: "right",
                  }}
                >
                  {item.value}
                </Text>
              </View>
            ))}
          </View>
        )}
      </View>
    );
  };

  const BadgeCard = ({ badge }) => (
    <View
      style={{
        backgroundColor: badge.unlockedAt ? "#ffffff" : "#F8E9E7",
        borderRadius: 12,
        padding: 16,
        marginRight: 12,
        width: 120,
        alignItems: "center",
        borderWidth: 1,
        borderColor: badge.unlockedAt ? "#F8E9E7" : "#F0D9D5",
        opacity: badge.unlockedAt ? 1 : 0.55,
      }}
    >
      <View style={{ marginBottom: 8 }}>
        <badge.icon size={32} color={badge.unlockedAt ? "#781D11" : "#C4A8A4"} strokeWidth={1.5} />
      </View>

      <Text
        style={{
          fontFamily: fonts.semibold,
          fontSize: 12,
          color: "#781D11",
          textAlign: "center",
          marginBottom: 4,
        }}
      >
        {badge.name}
      </Text>

      <Text
        style={{
          fontFamily: fonts.regular,
          fontSize: 10,
          color: "#C4A8A4",
          textAlign: "center",
        }}
      >
        {badge.unlockedAt ? "Unlocked" : "Locked"}
      </Text>
    </View>
  );

  return (
    <View style={{ flex: 1, backgroundColor: "#FFF9F9" }}>
      <StatusBar style="light" />

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={{ paddingBottom: insets.bottom + 100 }}
        showsVerticalScrollIndicator={false}
      >
        <ProfileHeader />

        <View style={{ padding: 20 }}>
          {/* Quick Actions */}
          <Text
            style={{
              fontFamily: fonts.semibold,
              fontSize: 18,
              color: "#781D11",
              marginBottom: 16,
            }}
          >
            Quick Actions
          </Text>

          <QuickAction
            title="Export Health Data"
            subtitle="Download your complete health records"
            icon={Download}
            color="#059669"
            onPress={handleExportData}
          />

          <QuickAction
            title="Share Health Summary"
            subtitle="Share a summary with healthcare providers"
            icon={ShareIcon}
            color="#A9334D"
            onPress={handleShareHealthSummary}
          />

          <QuickAction
            title="Emergency Contacts"
            subtitle={`${emergencyContacts.length} contacts configured`}
            icon={Phone}
            color="#EF4444"
            onPress={() =>
              Alert.alert(
                "Emergency Contacts",
                "Emergency contact management coming soon!",
              )
            }
          />

          {/* Health Records */}
          <Text
            style={{
              fontFamily: fonts.semibold,
              fontSize: 18,
              color: "#781D11",
              marginTop: 24,
              marginBottom: 16,
            }}
          >
            Health Records
          </Text>

          {healthRecordSections.map((section) => (
            <HealthRecordSection key={section.id} section={section} />
          ))}

          {/* Achievements */}
          <Text
            style={{
              fontFamily: fonts.semibold,
              fontSize: 18,
              color: "#781D11",
              marginTop: 24,
              marginBottom: 16,
            }}
          >
            Achievements
          </Text>

          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={{ paddingRight: 20 }}
            style={{ marginBottom: 24 }}
          >
            {mockBadges.map((badge) => (
              <BadgeCard key={badge.id} badge={badge} />
            ))}
          </ScrollView>

          {/* Settings & Support */}
          <Text
            style={{
              fontFamily: fonts.semibold,
              fontSize: 18,
              color: "#781D11",
              marginBottom: 16,
            }}
          >
            Settings & Support
          </Text>

          <QuickAction
            title="App Settings"
            subtitle="Notifications, privacy, and preferences"
            icon={Settings}
            color="#6B7280"
            onPress={() =>
              Alert.alert("Settings", "Settings screen coming soon!")
            }
          />

          <QuickAction
            title="Help & Support"
            subtitle="Get help and contact support"
            icon={FileText}
            color="#0EA5E9"
            onPress={() => Alert.alert("Support", "Help center coming soon!")}
          />

          <QuickAction
            title="Sign Out"
            subtitle="Sign out of your account"
            icon={LogOut}
            color="#DC2626"
            onPress={() => {
              Alert.alert("Sign Out", "Are you sure you want to sign out?", [
                { text: "Cancel", style: "cancel" },
                {
                  text: "Sign Out",
                  style: "destructive",
                  onPress: () =>
                    Alert.alert(
                      "Signed Out",
                      "You have been signed out successfully.",
                    ),
                },
              ]);
            }}
          />

          {/* App Info */}
          <View
            style={{
              alignItems: "center",
              marginTop: 24,
              paddingTop: 24,
              borderTopWidth: 1,
              borderTopColor: "#F8E9E7",
            }}
          >
            <Text
              style={{
                fontFamily: fonts.semibold,
                fontSize: 12,
                color: "#A9334D",
                marginBottom: 4,
              }}
            >
              Hemo
            </Text>
            <Text
              style={{
                fontFamily: fonts.regular,
                fontSize: 12,
                color: "#C4A8A4",
              }}
            >
              Version 1.0.0 • Build 100
            </Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}
