import React, { useState } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Alert,
  Share,
} from "react-native";
import { StatusBar } from "expo-status-bar";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  User,
  Settings,
  FileText,
  Download,
  Share as ShareIcon,
  ChevronDown,
  ChevronRight,
  Calendar,
  Activity,
  Heart,
  Award,
  LogOut,
  Edit,
  Phone,
  Shield,
} from "lucide-react-native";
import { useAppStore } from "../../store/appStore";
import { mockBadges } from "../../types";

export default function ProfileScreen() {
  const insets = useSafeAreaInsets();
  const [expandedSection, setExpandedSection] = useState(null);

  const { currentUser, healthStreak, emergencyContacts } = useAppStore();

  const toggleSection = (section) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  const handleShareHealthSummary = async () => {
    try {
      const summary = `
SickleCell Compass - Health Summary
Patient: ${currentUser?.name}
Age: ${currentUser?.age}
SCD Type: ${currentUser?.scdType}
Health Streak: ${healthStreak} days
Date: ${new Date().toLocaleDateString()}

This summary was generated by SickleCell Compass mobile app.
      `.trim();

      await Share.share({
        message: summary,
        title: "Health Summary",
      });
    } catch (error) {
      Alert.alert("Error", "Unable to share health summary");
    }
  };

  const handleExportData = () => {
    Alert.alert(
      "Export Health Data",
      "Your health data will be prepared for download. You will receive a comprehensive PDF report.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Export",
          onPress: () =>
            Alert.alert("Success", "Health data export initiated!"),
        },
      ],
    );
  };

  const healthRecordSections = [
    {
      id: "diagnosis",
      title: "Diagnosis Information",
      icon: FileText,
      color: "#DC2626",
      items: [
        { label: "Primary Diagnosis", value: "Sickle Cell Anemia (SS)" },
        { label: "Date of Diagnosis", value: "March 15, 2010" },
        { label: "Diagnosing Physician", value: "Dr. Sarah Johnson" },
        { label: "Current Status", value: "Stable, Managing Well" },
      ],
    },
    {
      id: "medications",
      title: "Current Medications",
      icon: Heart,
      color: "#059669",
      items: [
        { label: "Hydroxyurea", value: "500mg daily" },
        { label: "Folic Acid", value: "5mg daily" },
        { label: "Pain Management", value: "As needed" },
        { label: "Last Review", value: "November 1, 2024" },
      ],
    },
    {
      id: "allergies",
      title: "Allergies & Reactions",
      icon: Shield,
      color: "#EF4444",
      items: [
        { label: "Drug Allergies", value: "Codeine (severe reaction)" },
        { label: "Environmental", value: "None known" },
        { label: "Food Allergies", value: "None known" },
        { label: "Last Updated", value: "August 20, 2024" },
      ],
    },
    {
      id: "vaccinations",
      title: "Vaccination History",
      icon: Activity,
      color: "#7C3AED",
      items: [
        { label: "Pneumococcal", value: "Up to date (2024)" },
        { label: "Meningococcal", value: "Due for booster" },
        { label: "Influenza", value: "Annual - Current" },
        { label: "COVID-19", value: "Boosted (Sept 2024)" },
      ],
    },
  ];

  const ProfileHeader = () => (
    <View
      style={{
        backgroundColor: "#DC2626",
        paddingTop: insets.top + 20,
        paddingHorizontal: 20,
        paddingBottom: 30,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
      }}
    >
      <View
        style={{
          flexDirection: "row",
          alignItems: "center",
          marginBottom: 20,
        }}
      >
        <View
          style={{
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 40,
            padding: 20,
            marginRight: 16,
          }}
        >
          <User size={32} color="#ffffff" />
        </View>

        <View style={{ flex: 1 }}>
          <Text
            style={{
              fontSize: 24,
              fontWeight: "bold",
              color: "#ffffff",
              marginBottom: 4,
            }}
          >
            {currentUser?.name}
          </Text>

          <Text
            style={{
              fontSize: 16,
              color: "#FCA5A5",
              marginBottom: 2,
            }}
          >
            Age {currentUser?.age} • {currentUser?.scdType}
          </Text>

          <Text
            style={{
              fontSize: 14,
              color: "#FCA5A5",
            }}
          >
            Member since {currentUser?.createdAt?.toLocaleDateString()}
          </Text>
        </View>

        <TouchableOpacity
          style={{
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 10,
            padding: 10,
          }}
        >
          <Edit size={20} color="#ffffff" />
        </TouchableOpacity>
      </View>

      {/* Stats Row */}
      <View
        style={{
          flexDirection: "row",
          justifyContent: "space-around",
          backgroundColor: "rgba(255,255,255,0.1)",
          borderRadius: 16,
          paddingVertical: 16,
        }}
      >
        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontSize: 24,
              fontWeight: "bold",
              color: "#ffffff",
            }}
          >
            {healthStreak}
          </Text>
          <Text
            style={{
              fontSize: 12,
              color: "#FCA5A5",
            }}
          >
            Day Streak
          </Text>
        </View>

        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontSize: 24,
              fontWeight: "bold",
              color: "#ffffff",
            }}
          >
            89
          </Text>
          <Text
            style={{
              fontSize: 12,
              color: "#FCA5A5",
            }}
          >
            Total Logs
          </Text>
        </View>

        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontSize: 24,
              fontWeight: "bold",
              color: "#ffffff",
            }}
          >
            3
          </Text>
          <Text
            style={{
              fontSize: 12,
              color: "#FCA5A5",
            }}
          >
            Badges
          </Text>
        </View>

        <View style={{ alignItems: "center" }}>
          <Text
            style={{
              fontSize: 24,
              fontWeight: "bold",
              color: "#ffffff",
            }}
          >
            45
          </Text>
          <Text
            style={{
              fontSize: 12,
              color: "#FCA5A5",
            }}
          >
            Days Active
          </Text>
        </View>
      </View>
    </View>
  );

  const QuickAction = ({ title, subtitle, icon: Icon, color, onPress }) => (
    <TouchableOpacity
      onPress={onPress}
      style={{
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#F3F4F6",
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
      }}
    >
      <View
        style={{
          backgroundColor: `${color}15`,
          borderRadius: 10,
          padding: 12,
          marginRight: 16,
        }}
      >
        <Icon size={22} color={color} />
      </View>

      <View style={{ flex: 1 }}>
        <Text
          style={{
            fontSize: 16,
            fontWeight: "600",
            color: "#111827",
            marginBottom: 2,
          }}
        >
          {title}
        </Text>
        <Text
          style={{
            fontSize: 13,
            color: "#6B7280",
          }}
        >
          {subtitle}
        </Text>
      </View>

      <ChevronRight size={20} color="#9CA3AF" />
    </TouchableOpacity>
  );

  const HealthRecordSection = ({ section }) => {
    const isExpanded = expandedSection === section.id;

    return (
      <View
        style={{
          backgroundColor: "#ffffff",
          borderRadius: 12,
          marginBottom: 12,
          borderWidth: 1,
          borderColor: "#F3F4F6",
          overflow: "hidden",
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.05,
          shadowRadius: 3,
          elevation: 2,
        }}
      >
        <TouchableOpacity
          onPress={() => toggleSection(section.id)}
          style={{
            padding: 16,
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: isExpanded ? `${section.color}05` : "#ffffff",
          }}
        >
          <View
            style={{
              backgroundColor: `${section.color}15`,
              borderRadius: 8,
              padding: 8,
              marginRight: 12,
            }}
          >
            <section.icon size={20} color={section.color} />
          </View>

          <Text
            style={{
              fontSize: 16,
              fontWeight: "600",
              color: "#111827",
              flex: 1,
            }}
          >
            {section.title}
          </Text>

          {isExpanded ? (
            <ChevronDown size={20} color="#6B7280" />
          ) : (
            <ChevronRight size={20} color="#6B7280" />
          )}
        </TouchableOpacity>

        {isExpanded && (
          <View
            style={{
              paddingHorizontal: 16,
              paddingBottom: 16,
              borderTopWidth: 1,
              borderTopColor: "#F3F4F6",
            }}
          >
            {section.items.map((item, index) => (
              <View
                key={index}
                style={{
                  flexDirection: "row",
                  justifyContent: "space-between",
                  paddingVertical: 8,
                  borderBottomWidth: index < section.items.length - 1 ? 1 : 0,
                  borderBottomColor: "#F9FAFB",
                }}
              >
                <Text
                  style={{
                    fontSize: 14,
                    color: "#6B7280",
                    flex: 1,
                  }}
                >
                  {item.label}:
                </Text>
                <Text
                  style={{
                    fontSize: 14,
                    fontWeight: "500",
                    color: "#111827",
                    flex: 2,
                    textAlign: "right",
                  }}
                >
                  {item.value}
                </Text>
              </View>
            ))}
          </View>
        )}
      </View>
    );
  };

  const BadgeCard = ({ badge }) => (
    <View
      style={{
        backgroundColor: badge.unlockedAt ? "#ffffff" : "#F9FAFB",
        borderRadius: 12,
        padding: 16,
        marginRight: 12,
        width: 120,
        alignItems: "center",
        borderWidth: 1,
        borderColor: badge.unlockedAt ? "#F3F4F6" : "#E5E7EB",
        opacity: badge.unlockedAt ? 1 : 0.6,
      }}
    >
      <Text
        style={{
          fontSize: 32,
          marginBottom: 8,
        }}
      >
        {badge.icon}
      </Text>

      <Text
        style={{
          fontSize: 12,
          fontWeight: "600",
          color: "#111827",
          textAlign: "center",
          marginBottom: 4,
        }}
      >
        {badge.name}
      </Text>

      <Text
        style={{
          fontSize: 10,
          color: "#6B7280",
          textAlign: "center",
        }}
      >
        {badge.unlockedAt ? "Unlocked" : "Locked"}
      </Text>
    </View>
  );

  return (
    <View style={{ flex: 1, backgroundColor: "#F9FAFB" }}>
      <StatusBar style="light" />

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={{ paddingBottom: insets.bottom + 100 }}
        showsVerticalScrollIndicator={false}
      >
        <ProfileHeader />

        <View style={{ padding: 20 }}>
          {/* Quick Actions */}
          <Text
            style={{
              fontSize: 18,
              fontWeight: "600",
              color: "#111827",
              marginBottom: 16,
            }}
          >
            Quick Actions
          </Text>

          <QuickAction
            title="Export Health Data"
            subtitle="Download your complete health records"
            icon={Download}
            color="#059669"
            onPress={handleExportData}
          />

          <QuickAction
            title="Share Health Summary"
            subtitle="Share a summary with healthcare providers"
            icon={ShareIcon}
            color="#7C3AED"
            onPress={handleShareHealthSummary}
          />

          <QuickAction
            title="Emergency Contacts"
            subtitle={`${emergencyContacts.length} contacts configured`}
            icon={Phone}
            color="#EF4444"
            onPress={() =>
              Alert.alert(
                "Emergency Contacts",
                "Emergency contact management coming soon!",
              )
            }
          />

          {/* Health Records */}
          <Text
            style={{
              fontSize: 18,
              fontWeight: "600",
              color: "#111827",
              marginTop: 24,
              marginBottom: 16,
            }}
          >
            Health Records
          </Text>

          {healthRecordSections.map((section) => (
            <HealthRecordSection key={section.id} section={section} />
          ))}

          {/* Achievements */}
          <Text
            style={{
              fontSize: 18,
              fontWeight: "600",
              color: "#111827",
              marginTop: 24,
              marginBottom: 16,
            }}
          >
            Achievements
          </Text>

          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={{ paddingRight: 20 }}
            style={{ marginBottom: 24 }}
          >
            {mockBadges.map((badge) => (
              <BadgeCard key={badge.id} badge={badge} />
            ))}
          </ScrollView>

          {/* Settings & Support */}
          <Text
            style={{
              fontSize: 18,
              fontWeight: "600",
              color: "#111827",
              marginBottom: 16,
            }}
          >
            Settings & Support
          </Text>

          <QuickAction
            title="App Settings"
            subtitle="Notifications, privacy, and preferences"
            icon={Settings}
            color="#6B7280"
            onPress={() =>
              Alert.alert("Settings", "Settings screen coming soon!")
            }
          />

          <QuickAction
            title="Help & Support"
            subtitle="Get help and contact support"
            icon={FileText}
            color="#0EA5E9"
            onPress={() => Alert.alert("Support", "Help center coming soon!")}
          />

          <QuickAction
            title="Sign Out"
            subtitle="Sign out of your account"
            icon={LogOut}
            color="#DC2626"
            onPress={() => {
              Alert.alert("Sign Out", "Are you sure you want to sign out?", [
                { text: "Cancel", style: "cancel" },
                {
                  text: "Sign Out",
                  style: "destructive",
                  onPress: () =>
                    Alert.alert(
                      "Signed Out",
                      "You have been signed out successfully.",
                    ),
                },
              ]);
            }}
          />

          {/* App Info */}
          <View
            style={{
              alignItems: "center",
              marginTop: 24,
              paddingTop: 24,
              borderTopWidth: 1,
              borderTopColor: "#E5E7EB",
            }}
          >
            <Text
              style={{
                fontSize: 12,
                color: "#9CA3AF",
                marginBottom: 4,
              }}
            >
              SickleCell Compass
            </Text>
            <Text
              style={{
                fontSize: 12,
                color: "#9CA3AF",
              }}
            >
              Version 1.0.0 • Build 100
            </Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}
