import { useMemo } from "react";
import { Sparkles } from "lucide-react";
import { Card } from "@/components/ui/card";
import type { HealthSummaryData } from "@/components/pdfx/HealthSummaryDocument";

type AiInsight = NonNullable<HealthSummaryData["aiInsights"]>[number];
type Tone = AiInsight["tone"];

const TONE_PRIORITY: Record<Tone, number> = {
  danger: 0,
  warning: 1,
  info: 2,
  success: 3,
};

const TONE_LABEL: Record<Tone, string> = {
  danger: "Action needed",
  warning: "Watch",
  info: "Note",
  success: "Positive",
};

const TONE_ACCENT: Record<Tone, string> = {
  danger: "#DC2626",
  warning: "#F0531C",
  info: "#1F6EDC",
  success: "#1F8A5B",
};

const HEMO_GRADIENT =
  "linear-gradient(135deg, #D09F9A 0%, #A9334D 50%, #781D11 100%)";

// ── AI Synthesis card ─────────────────────────────────────────────────────────

export function SummarySynthesisCard({ data }: { data: HealthSummaryData }) {
  const synthesis = useMemo(() => buildSynthesis(data), [data]);

  return (
    <div className="mx-auto max-w-[960px] px-6 max-sm:px-4">
      <Card className="relative z-[2] -mt-9 grid grid-cols-[56px_1fr] items-start gap-6 rounded-[20px] border-[#F0E4E1] bg-white px-9 py-8 shadow-[0_1px_8px_rgba(0,0,0,0.06)] max-sm:-mt-7 max-sm:grid-cols-[40px_1fr] max-sm:gap-4 max-sm:p-6">
        <div
          className="flex size-14 shrink-0 items-center justify-center rounded-[16px] text-white shadow-[0_6px_16px_rgba(169,51,77,0.20)] max-sm:size-10 max-sm:rounded-[12px]"
          style={{ background: HEMO_GRADIENT }}
          aria-hidden
        >
          <Sparkles className="size-5" />
        </div>

        <div>
          <div className="mb-2.5 inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[1.4px] text-[#A9334D]">
            <span className="inline-block h-px w-3.5 bg-[#A9334D]" />
            The gist
          </div>
          <p className="m-0 text-[clamp(20px,2.4vw,24px)] font-medium leading-[1.4] tracking-[-0.5px] text-[#1A1414]">
            {synthesis}
          </p>
          <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-[12px] text-[#1A1414]/65">
            <span className="inline-flex items-center gap-1.5">
              <Sparkles className="size-3" /> Generated by Hemo's pattern
              recognition
            </span>
            <span className="size-[3px] rounded-full bg-[#1A1414]/30" />
            <span>
              Based on {data.stats.totalDaysLogged} self-reported daily logs
            </span>
          </div>
        </div>
      </Card>
    </div>
  );
}

function buildSynthesis(data: HealthSummaryData): React.ReactNode {
  const sorted = [...(data.aiInsights ?? [])].sort(
    (a, b) => TONE_PRIORITY[a.tone] - TONE_PRIORITY[b.tone],
  );
  const concern =
    sorted.find((i) => i.tone === "danger") ||
    sorted.find((i) => i.tone === "warning");
  const positive = sorted.find((i) => i.tone === "success");
  const clean = (s: string) => s.replace(/[.\s]+$/, "");

  return (
    <>
      Over <Em>{data.periodDays} days</Em>, with average pain at{" "}
      <Em>{(data.stats.avgPain ?? 0).toFixed(1)}/10</Em> across{" "}
      <Em>{data.stats.totalDaysLogged} logged days</Em>.
      {concern && (
        <>
          {" "}
          Hemo surfaced <Em>{(data.aiInsights ?? []).length} patterns</Em> —
          most urgent: {clean(concern.headline).toLowerCase()}.
        </>
      )}
      {positive && (
        <>
          {" "}
          The bright spot:{" "}
          <span className="font-semibold text-[#1F8A5B]">
            {clean(positive.headline).toLowerCase()}
          </span>
          .
        </>
      )}
    </>
  );
}

function Em({ children }: { children: React.ReactNode }) {
  return (
    <span className="font-semibold not-italic text-[#A9334D]">{children}</span>
  );
}

// ── "What we noticed" insights section ───────────────────────────────────────

export function SummaryInsightsSection({ data }: { data: HealthSummaryData }) {
  const insights = data.aiInsights ?? [];

  const sorted = useMemo(
    () =>
      [...insights].sort(
        (a, b) => TONE_PRIORITY[a.tone] - TONE_PRIORITY[b.tone],
      ),
    [insights],
  );

  if (!insights.length) return null;

  const counts: Partial<Record<Tone, number>> = {};
  for (const i of sorted) counts[i.tone] = (counts[i.tone] ?? 0) + 1;

  const COUNT_LABEL: Record<Tone, (n: number) => string> = {
    danger: () => "urgent",
    warning: () => "to watch",
    info: () => "notes",
    success: (n) => (n > 1 ? "positives" : "positive"),
  };

  const first =
    data.profile?.nickname ||
    data.profile?.full_name?.split(" ")[0] ||
    "the patient";

  return (
    <section className="pt-14 max-sm:pt-10">
      <div className="mx-auto max-w-[960px] px-6 max-sm:px-4">
        <div className="mb-5 flex items-end justify-between gap-4">
          <div>
            <div className="mb-1.5 text-[11px] font-semibold uppercase tracking-[1.4px] text-[#1A1414]/65">
              Pattern recognition
            </div>
            <h2 className="m-0 text-[clamp(22px,2.4vw,28px)] font-bold tracking-[-0.8px] text-[#781D11]">
              What we noticed
            </h2>
          </div>
          <div className="inline-flex flex-wrap items-center gap-x-3.5 gap-y-1 text-[13px] tracking-[-0.1px] text-[#1A1414]/65">
            {(["danger", "warning", "info", "success"] as const).map((tone) =>
              counts[tone] ? (
                <span key={tone}>
                  <span
                    className="mr-1.5 inline-block size-2 rounded-full align-middle"
                    style={{ background: TONE_ACCENT[tone] }}
                  />
                  <b className="font-mono font-semibold text-[#1A1414]">
                    {counts[tone]}
                  </b>{" "}
                  {COUNT_LABEL[tone](counts[tone]!)}
                </span>
              ) : null,
            )}
          </div>
        </div>

        <div className="flex flex-col gap-3.5">
          {sorted.map((insight, i) => (
            <InsightCard
              key={i}
              insight={insight}
              index={i + 1}
              total={sorted.length}
            />
          ))}
        </div>

        <div className="mt-7 flex items-start gap-2.5 rounded-[16px] px-4 py-3.5 text-[12px] leading-normal text-[#1A1414]/65">
          <Sparkles className="size-3.5 shrink-0 text-[#A9334D]" />
          <div>
            <b className="font-semibold text-[#1A1414]">
              About these insights.
            </b>{" "}
            Patterns are generated automatically from {first}'s self-reported
            daily logs. They are not a clinical diagnosis. Always discuss
            findings with your care team before changing medication or
            treatment.
          </div>
        </div>
      </div>
    </section>
  );
}

function InsightCard({
  insight,
  index,
  total,
}: {
  insight: AiInsight;
  index: number;
  total: number;
}) {
  const accent = TONE_ACCENT[insight.tone];

  return (
    <article className="flex gap-7 rounded-2xl border border-[#F0E4E1] bg-white px-8 py-7 max-sm:gap-4 max-sm:px-5 max-sm:py-5">
      {/* Large index number in tone color */}
      <div
        className="shrink-0 font-mono text-[72px] font-bold leading-none tracking-[-2px] max-sm:text-[52px]"
        style={{ color: accent }}
      >
        {String(index).padStart(2, "0")}
      </div>

      {/* Content */}
      <div className="min-w-0 flex-1 pt-1">
        {/* Meta row: dot + metric | tone label ... counter */}
        <div className="mb-3 flex items-center">
          <span className="inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[1.3px] text-[#1A1414]">
            <span
              className="size-1.5 shrink-0 rounded-full"
              style={{ background: accent }}
            />
            {insight.metric}
          </span>
          <span className="mx-2.5 text-[#1A1414]/20">|</span>
          <span
            className="text-[11px] font-semibold uppercase tracking-[1.3px]"
            style={{ color: accent }}
          >
            {TONE_LABEL[insight.tone]}
          </span>
          <span className="ml-auto font-mono text-[12px] text-[#1A1414]/30">
            {String(index).padStart(2, "0")} / {String(total).padStart(2, "0")}
          </span>
        </div>

        <h3 className="m-0 mb-3 text-[clamp(18px,1.6vw,22px)] font-bold leading-[1.3] tracking-[-0.5px] text-[#1A1414]">
          {insight.headline}
        </h3>
        <p className="m-0 text-[15px] leading-[1.6] text-[#1A1414]/55">
          {insight.detail}
        </p>
      </div>
    </article>
  );
}
